#spring:
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost/5432/click
#    username: postgres
#    password: 1998
#    hikari:
#      maximum-pool-size: 20
#      minimum-idle: 10
#      idle-timeout: 60
#  jpa:
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        format_sql: true
#        show_sql: true